/**
 *
 * $Id$
 */
package org.openhealthtools.ihe.xds.response.response.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.ihe.xds.response.response.XDSErrorListType;
import org.openhealthtools.ihe.xds.response.response.XDSErrorType;
import org.openhealthtools.ihe.xds.response.response.XDSQueryResponseType;
import org.openhealthtools.ihe.xds.response.response.XDSResponseType;

/**
 * A sample validator interface for {@link org.openhealthtools.ihe.xds.response.response.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap value);
	boolean validateXSISchemaLocation(EMap value);
	boolean validateXDSError(XDSErrorType value);
	boolean validateXDSErrorList(XDSErrorListType value);
	boolean validateXDSQueryResponse(XDSQueryResponseType value);
	boolean validateXDSResponse(XDSResponseType value);
}
