/**
 *
 * $Id$
 */
package org.openhealthtools.ihe.xds.response.response.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.ihe.xds.response.response.XDSStatusType;

/**
 * A sample validator interface for {@link org.openhealthtools.ihe.xds.response.response.XDSErrorListType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XDSErrorListTypeValidator {
	boolean validate();

	boolean validateError(EList value);
	boolean validateHighestSeverity(XDSStatusType value);
}
