/**
 *
 * $Id$
 */
package org.openhealthtools.ihe.common.hl7v2.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.openhealthtools.ihe.common.hl7v2.CX;
import org.openhealthtools.ihe.common.hl7v2.CXi;
import org.openhealthtools.ihe.common.hl7v2.SourcePatientInfoType;
import org.openhealthtools.ihe.common.hl7v2.XAD;
import org.openhealthtools.ihe.common.hl7v2.XCN;
import org.openhealthtools.ihe.common.hl7v2.XON;
import org.openhealthtools.ihe.common.hl7v2.XPN;
import org.openhealthtools.ihe.common.hl7v2.XTN;

/**
 * A sample validator interface for {@link org.openhealthtools.ihe.common.hl7v2.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap value);
	boolean validateXSISchemaLocation(EMap value);
	boolean validateCx(CX value);
	boolean validateCxi(CXi value);

	boolean validateDtm(String value);
	boolean validateSourcePatientInfo(SourcePatientInfoType value);
	boolean validateXad(XAD value);
	boolean validateXcn(XCN value);
	boolean validateXon(XON value);
	boolean validateXpn(XPN value);
	boolean validateXtn(XTN value);
}
