/**
 *
 * $Id$
 */
package org.openhealthtools.ihe.common.hl7v2.validation;

import org.eclipse.emf.common.util.EList;

import org.openhealthtools.ihe.common.hl7v2.XAD;
import org.openhealthtools.ihe.common.hl7v2.XTN;

/**
 * A sample validator interface for {@link org.openhealthtools.ihe.common.hl7v2.SourcePatientInfoType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourcePatientInfoTypeValidator {
	boolean validate();

	boolean validatePatientIdentifier(EList value);
	boolean validatePatientName(EList value);
	boolean validatePatientDateOfBirth(String value);
	boolean validatePatientSex(String value);
	boolean validatePatientAddress(XAD value);
	boolean validatePatientPhoneHome(XTN value);
	boolean validatePatientPhoneBusiness(XTN value);
}
