/**
 *
 * $Id$
 */
package org.openhealthtools.ihe.common.hl7v2.validation;


/**
 * A sample validator interface for {@link org.openhealthtools.ihe.common.hl7v2.XTN}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XTNValidator {
	boolean validate();

	boolean validateTelecommunicationType(String value);
	boolean validateTelecommunicationAddress(String value);
}
